### ISSUE TITLE
multistream goes a bit nuts when sockets hangup while it is doing its thing

### ISSUE THREAD

**Issue by daviddias** [multiformats/js-multistream-select#35]
![image](https://cloud.githubusercontent.com/assets/1211152/22856412/ae56e4fc-f045-11e6-9dca-6bb852ba6823.png)

**Comment by diasdavid** [comment]
We really need to model swarm as a big state machine https://github.com/libp2p/js-libp2p-swarm/issues/24, otherwise finding the causes for these issues is like looking for needles in haystacks

**Comment by michaelfakhri** [comment]
I have seen this error previously and in my case, it occurred when the browser was closed. The error seems to be propagated through the pull-stream and I previously traced it back to the following:
https://github.com/spdy-http2/spdy-transport/blob/master/lib/spdy-transport/connection.js#L180

How I am handling it? I have a drain in my pull-stream which actually catches that error and will probably handle it there at some point. 

What I think you're seeing is probably the lack of a drain or other error handler causing it to explode (Maybe?) I don't think this is particularly ms-select's fault here. I personally think the application or module at the end of the stream should catch this error and end the pull-stream.

**Comment by jacobheun** [comment]
Closing this as stale. This should no longer be an issue as of the 0.15 refactor.
