### ISSUE TITLE
`ls` drains the connection so we cannot perform other operations on the same connection

### ISSUE THREAD

**Issue by Mikerah** [multiformats/js-multistream-select#47]
I was attempting to use `ls` and `select` in a project. However, after discussing with @jacobheun, it became clearer that `ls` drains a connection so that performing another operation such as `select` on the same connection is no longer possible.

**Comment by jacobheun** [comment]
The ideal logic for this would look something like:

```js
// create the dialer
const dialer = new multistream.Dialer()
// wrap the existing connection
await dialer.handle(baseConnection)
// get a list of supported protocols from the receiver
const supportedProtocols = await dialer.ls()
// determine the protocol we want to use, and that we both support
const desiredProtocol = getDesiredProtocol(supportedProtocols)
// get a stream for the desiredProtocol
const stream = await dialer.select(desiredProtocol)
// Act on the stream
...
```

Since `ls` ends in a collect, we're prevented from performing a `select` on the same connection. Ideally `ls` would just be a handshake so the stream can continue to be used without custom logic by the user.

**Comment by jacobheun** [comment]
This is possibly as of the 0.15 refactor.

```js
const mss = new MSS.Dialer(duplex)
const lsProtocols = await mss.ls()
const { stream, protocol } = await mss.select('/my/protocol')
```
