### ISSUE TITLE
Bug when messages are pipelined

### ISSUE THREAD

**Issue by Stebalien** [multiformats/js-multistream-select#48]
From https://github.com/ipfs/go-ipfs/issues/6389#issuecomment-497233489

---

In https://github.com/multiformats/go-multistream/pull/32, go started pipelining protocol negotiation. Specifically, instead of:

1. Client sends server `/multistream/1.0.0`
2. Server sends client `/multistream/1.0.0`
3. Client sends server the first protocol.
4. Server sends client `na` or the protocol (if selected).

The protocol now looks like:

1. Client sends server `/multistream/1.0.0`
2. Client sends server the first protocol.
3. Server sends client `/multistream/1.0.0`
4. Server sends client `na` or the protocol (if selected).

That way, we can half to a full round trip (depending on the server's implementation).

However, this appears to be causing the connection to fail with:

> Error: Dial is currently blacklisted for this peer

(an error from javascript).

But I can't reproduce this issue when I manually spin up a js-ipfs node and a go-ipfs node.

Also note, adding a small delay between sending the `/multistream/1.0.0` header and the first protocol appears to fix the issue.

---

To reproduce, run the "exchange-files" interop test against go-ipfs 0.4.21-rc3.

**Comment by jacobheun** [comment]
This is not a bug with multistream-select. Context at https://github.com/ipfs/go-ipfs/issues/6389#issuecomment-497465039
